first=("Golden ", "Silver ", "Renagade ", "Sir ", "Elite ", "Enforcer ", "Calibre ")
last=("A-Treak ", "Steve ", "AAA ", "Sal ", "Jil ", "Matt", "Tulious")
import random as r
A=r.choice(first)
B=r.choice(last)
name=(A+B)
print("You have encountered ",name,"As an opposition!")
import time as t
hp=15
e_hp=10
m=2
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win
e_dmg=r.randint(1,5)
hp=(hp-e_dmg)
if hp==(0): exit("Your ship has been killed by ", name,)
print("You have", hp, "hull")
dmg=r.randint(1,5)
print("Would you like to fire a missile? you have ", m," Missiles (Put in Y or N)")
c=input()
if c==("Y"): e_hp=(e_hp-7)
if c==("N"): e_hp=(e_hp-dmg)
if m==0: print("NO MISSILES LEFT")
if e_hp==0: from interdiction import win