print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
print("WELCOME TO McGraith Gateway")
print("YOUR SHIP")
print("Fuel: INF")
print("Hull: Conditional INF")
print("Ammo: Conditional INF")
print("STATION STATS")
print("Owner: SqueezyS")
print("Government: Democracy")
print("State(s): Economic Boom/Economic Inflation")
print("Economy: Mass Production")

print("What do you want to do?")
print("A: Leave Station")
print("B: Gain info on aliens")
a=input()
if a == ("A"): from AxAxA import supercruise
if a == ("B"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")
if a == ("a"): from AxAxA import supercruise
if a == ("b"): print("BRODCAST: We have no idea who they are but they can be DESTRUCTIVE")